# Generated by Django 4.0 on 2024-12-08 07:27

import App_Inventory.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('Attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Inventory.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('is_addons', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('Category_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('quantity', models.IntegerField(default=0)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Location', models.CharField(blank=True, max_length=255, null=True)),
                ('action_details', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('AttributeTerm', models.ManyToManyField(blank=True, related_name='Attribute_Term', related_query_name='Attribute_Term', to='App_Inventory.AttributeTerm')),
                ('Brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Brand', related_query_name='Brand', to='App_Inventory.brand')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Item_Category', related_query_name='Item_Category', to='App_Inventory.category')),
                ('Sub_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_Sub_Category', related_query_name='Product_Sub_Category', to='App_Inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Tag_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Inventory.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('costing', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Inventory.items')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(blank=True, max_length=255, null=True)),
                ('Supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('quantity', models.IntegerField(default=0)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('action_details', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('AttributeTerm', models.ManyToManyField(blank=True, related_name='AttributeVariation', related_query_name='AttributeVariation', to='App_Inventory.AttributeTerm')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemVariation', related_query_name='ItemVariation', to='App_Inventory.items')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='Tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tag', related_query_name='Tag', to='App_Inventory.tag'),
        ),
        migrations.AddField(
            model_name='items',
            name='related_Items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Inventory.items'),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to=App_Inventory.models.item_image_file_path)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('AttributeTerm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Inventory.attributeterm')),
                ('Item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Inventory.items')),
                ('ItemVariation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Inventory.itemvariation')),
            ],
        ),
    ]
